Push Code
catdemian/nodered-ansible-terraform-packer-aws pull request #1
Opened 2018-11-09 00:02 UTC by catdemian

2018-11-09 01:56 UTC, diegows requested changes
Check inline comments.

2018-11-09 01:56 UTC, diegows commented on README.md
> +2. Provide subnet_id  in the packer.json file with the value of "aws_subnet_output" just gathered before.  `vi vi packer.json`
Can we use environment variables to avoid modifications on files on git?

2018-11-09 01:56 UTC, diegows commented on packer/packer.json
> +    "aws_access_key": "Your AWS access key",
Environment variables here are better, to avoid pushing secrets to the repo accidentally.

2018-11-09 01:56 UTC, diegows commented on packer/packer.json
> +      "access_key": "{{user `aws_access_key`}}",
same here

2018-11-09 01:56 UTC, diegows commented on terraform-net/variables.tf
> +variable "secret_key" {
same here

2018-11-10 21:55 UTC, catdemian commented
All suggestions are already implemented.

2018-11-11 01:59 UTC, diegows approved these changes

2018-11-16 16:57 UTC, merged